package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Terminal generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Long id;
     private String datacard;
     private String pin;
     private String name;
     private Merchant merchant;

    public Account() {
    }
    
	public Account(Long id, String datacard, String pin, Merchant merchant) {
		super();
		this.id = id;
		this.datacard = datacard;
		this.pin = pin;
		this.merchant = merchant;
	}

	public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public void setMerchant(Merchant merchant) {
        this.merchant = merchant;
    }
	public String getDatacard() {
		return datacard;
	}
	public void setDatacard(String datacard) {
		this.datacard = datacard;
	}
	public String getPin() {
		return pin;
	}
	public void setPin(String pin) {
		this.pin = pin;
	}
	public Merchant getMerchant() {
		return merchant;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
    
}


