package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Terminal generated by hbm2java
 */
public class ApiSystem  implements java.io.Serializable {


     private Long id;
     private Boolean maintanance;

    public ApiSystem() {
    }
    
	public ApiSystem(Long id, Boolean maintanance) {
		super();
		this.id = id;
		this.maintanance = maintanance;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Boolean getMaintanance() {
		return maintanance;
	}

	public void setMaintanance(Boolean maintanance) {
		this.maintanance = maintanance;
	}
}


