package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.List;
import java.util.HashSet;
import java.util.Set;

import org.codehaus.jettison.json.JSONArray;
import org.codehaus.jettison.json.JSONException;
import org.codehaus.jettison.json.JSONObject;
import org.jpos.ee.DB;

import id.co.keriss.consolidate.dao.BankDao;

/**
 * Bank generated by hbm2java
 */
public class Bank  implements java.io.Serializable {


     private long id;
     private String name;
     private String bank_code;
     private String rekening;
     private boolean aquirer;
   //list bank
 	static final String[] BANK1=new String[] {"Bank BCA", "781111111111" };

 	public JSONArray getListBank(DB db) {	
 		JSONArray bankList=new JSONArray();
 		
 		BankDao bankDao=new BankDao(db);
 		List<Bank> listBank=bankDao.getListBank();
 		
 		for(Bank bank: listBank) {
 			JSONObject bank1=new JSONObject();
 	 		try {
 	 			bank1.put("nama", bank.getName());
 	 			bank1.put("rek", bank.getRekening());
 	 			bankList.put(bank1);
 	 		} catch (JSONException e) {
 	 			// TODO Auto-generated catch block
 	 			e.printStackTrace();
 	 		}		
 		}
 		
 	
 		return bankList;
 		
 	}
 	
 	public boolean existRek(String rek) {	
 	
 		return true;
 	}
 	
 
    public Bank() {
    }

    public Bank(String bank_code,String name, boolean aquirer) {
       this.name = name;
       this.aquirer = aquirer;
       this.bank_code=bank_code;
    }
   
    
    public String getBank_code() {
		return bank_code;
	}

	public void setBank_code(String bank_code) {
		this.bank_code = bank_code;
	}

	public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isAquirer() {
        return this.aquirer;
    }
    
    public void setAquirer(boolean aquirer) {
        this.aquirer = aquirer;
    }

	public String getRekening() {
		return rekening;
	}

	public void setRekening(String rekening) {
		this.rekening = rekening;
	}




}


