package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Card generated by hbm2java
 */
public class Card  implements java.io.Serializable {


     private Long id;
     private String cardno;
     private Long saldo;
     private Set card = new HashSet(0);

    public Card() {
    }

    public Card(String cardno, Long saldo, Set card) {
       this.cardno = cardno;
       this.saldo = saldo;
       this.card = card;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getCardno() {
        return this.cardno;
    }
    
    public void setCardno(String cardno) {
        this.cardno = cardno;
    }
    public Long getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Long saldo) {
        this.saldo = saldo;
    }
    public Set getCard() {
        return this.card;
    }
    
    public void setCard(Set card) {
        this.card = card;
    }




}


