package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cassa generated by hbm2java
 */
public class Cassa  implements java.io.Serializable {


     private Long id;
     private String name;
     private Store store;
     private Floor floor;
     private Set transaction = new HashSet(0);
     private Set edc = new HashSet(0);

    public Cassa() {
    }

    public Cassa(String name, Store store, Floor floor, Set transaction, Set edc) {
       this.name = name;
       this.store = store;
       this.floor = floor;
       this.transaction = transaction;
       this.edc = edc;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }
    public Floor getFloor() {
        return this.floor;
    }
    
    public void setFloor(Floor floor) {
        this.floor = floor;
    }
    public Set getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Set transaction) {
        this.transaction = transaction;
    }
    public Set getEdc() {
        return this.edc;
    }
    
    public void setEdc(Set edc) {
        this.edc = edc;
    }




}


