package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Terminal generated by hbm2java
 */
public class CurrentBalance  implements java.io.Serializable {


     private Long id;
     private BigDecimal balance;
     private String invoice_id;
     private String invoice_items_id;
     private Date created_date;
     
     
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public BigDecimal getBalance() {
		return balance;
	}
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}
	public String getInvoice_id() {
		return invoice_id;
	}
	public void setInvoice_id(String invoice_id) {
		this.invoice_id = invoice_id;
	}
	public String getInvoice_items_id() {
		return invoice_items_id;
	}
	public void setInvoice_items_id(String invoice_items_id) {
		this.invoice_items_id = invoice_items_id;
	}
	public Date getCreated_date() {
		return created_date;
	}
	public void setCreated_date(Date created_date) {
		this.created_date = created_date;
	}


}


