package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.text.DecimalFormat;
import java.util.HashSet;
import java.util.Set;

/**
 * Terminal generated by hbm2java
 */
public class DenomVO  implements java.io.Serializable {


     private int id;
     private int denom;
     private String denomS;
     
		public int getId() {
			return id;
		}
		public void setId(int id) {
			this.id = id;
		}
		public int getDenom() {
			return denom;
		}
		public void setDenom(int denom) {
			this.denom = denom;
			DecimalFormat myFormatter = new DecimalFormat("###,###.##");
	        denomS = myFormatter.format(denom*1000);
		}
		public String getDenomS() {
			return denomS;
		}
		
     
     
    
    
}


