package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Edc generated by hbm2java
 */
public class Edc  implements java.io.Serializable {


     private Long id;
     private String sn;
     private String model;
     private Cassa cassa;
     private Set terminal = new HashSet(0);

    public Edc() {
    }

    public Edc(String sn, String model, Cassa cassa, Set terminal) {
       this.sn = sn;
       this.model = model;
       this.cassa = cassa;
       this.terminal = terminal;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getSn() {
        return this.sn;
    }
    
    public void setSn(String sn) {
        this.sn = sn;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public Cassa getCassa() {
        return this.cassa;
    }
    
    public void setCassa(Cassa cassa) {
        this.cassa = cassa;
    }
    public Set getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Set terminal) {
        this.terminal = terminal;
    }




}


