package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import org.jpos.ee.User;

/**
 * Merchant generated by hbm2java
 */
/**
 * @author jarvis
 *
 */
public class Invoice implements java.io.Serializable {

	private long id_invoice;
	private String kb_invoice;
	private Date datetime;
	private Documents document;
	private long amount;
	private User eeuser; 
    private String external_key;
    private char tenant; 
    private char trx;
	
	public Invoice() {

	}

	public long getId_invoice() {
		return id_invoice;
	}



	public void setId_invoice(long id_invoice) {
		this.id_invoice = id_invoice;
	}



	public Date getDatetime() {
		return datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Documents getDocument() {
		return document;
	}

	public void setDocument(Documents document) {
		this.document = document;
	}

	public long getAmount() {
		return amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	public User getEeuser() {
		return eeuser;
	}

	public void setEeuser(User eeuser) {
		this.eeuser = eeuser;
	}

	public String getExternal_key() {
		return external_key;
	}

	public void setExternal_key(String external_key) {
		this.external_key = external_key;
	}

	public char getTenant() {
		return tenant;
	}

	public void setTenant(char tenant) {
		this.tenant = tenant;
	}

	public char getTrx() {
		return trx;
	}

	public void setTrx(char trx) {
		this.trx = trx;
	}

	public String getKb_invoice() {
		return kb_invoice;
	}

	public void setKb_invoice(String kb_invoice) {
		this.kb_invoice = kb_invoice;
	}

}
