package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Invoicing generated by hbm2java
 */
public class Invoicing  implements java.io.Serializable {


     private Long id;
     private String product;
     private int totaltrx;
     private Long totalgross;
     private int onustrx;
     private Long onusgross;
     private int offustrx;
     private Long offusgross;
     private Float mdronuspercent;
     private Long mdronus;
     private Float mdroffuspercent;
     private Long mdroffus;
     private Date dateday;
     private String bank;
     private Long totalmdr;

    public Invoicing() {
    }

    public Invoicing(String product, int totaltrx, Long totalgross, int onustrx, Long onusgross, int offustrx, Long offusgross, Float mdronuspercent, Long mdronus, Float mdroffuspercent, Long mdroffus, Date dateday, String bank, Long totalmdr) {
       this.product = product;
       this.totaltrx = totaltrx;
       this.totalgross = totalgross;
       this.onustrx = onustrx;
       this.onusgross = onusgross;
       this.offustrx = offustrx;
       this.offusgross = offusgross;
       this.mdronuspercent = mdronuspercent;
       this.mdronus = mdronus;
       this.mdroffuspercent = mdroffuspercent;
       this.mdroffus = mdroffus;
       this.dateday = dateday;
       this.bank = bank;
       this.totalmdr = totalmdr;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public int getTotaltrx() {
        return this.totaltrx;
    }
    
    public void setTotaltrx(int totaltrx) {
        this.totaltrx = totaltrx;
    }
    public Long getTotalgross() {
        return this.totalgross;
    }
    
    public void setTotalgross(Long totalgross) {
        this.totalgross = totalgross;
    }
    public int getOnustrx() {
        return this.onustrx;
    }
    
    public void setOnustrx(int onustrx) {
        this.onustrx = onustrx;
    }
    public Long getOnusgross() {
        return this.onusgross;
    }
    
    public void setOnusgross(Long onusgross) {
        this.onusgross = onusgross;
    }
    public int getOffustrx() {
        return this.offustrx;
    }
    
    public void setOffustrx(int offustrx) {
        this.offustrx = offustrx;
    }
    public Long getOffusgross() {
        return this.offusgross;
    }
    
    public void setOffusgross(Long offusgross) {
        this.offusgross = offusgross;
    }
    public Float getMdronuspercent() {
        return this.mdronuspercent;
    }
    
    public void setMdronuspercent(Float mdronuspercent) {
        this.mdronuspercent = mdronuspercent;
    }
    public Long getMdronus() {
        return this.mdronus;
    }
    
    public void setMdronus(Long mdronus) {
        this.mdronus = mdronus;
    }
    public Float getMdroffuspercent() {
        return this.mdroffuspercent;
    }
    
    public void setMdroffuspercent(Float mdroffuspercent) {
        this.mdroffuspercent = mdroffuspercent;
    }
    public Long getMdroffus() {
        return this.mdroffus;
    }
    
    public void setMdroffus(Long mdroffus) {
        this.mdroffus = mdroffus;
    }
    public Date getDateday() {
        return this.dateday;
    }
    
    public void setDateday(Date dateday) {
        this.dateday = dateday;
    }
    public String getBank() {
        return this.bank;
    }
    
    public void setBank(String bank) {
        this.bank = bank;
    }
    public Long getTotalmdr() {
        return this.totalmdr;
    }
    
    public void setTotalmdr(Long totalmdr) {
        this.totalmdr = totalmdr;
    }




}


