package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.bouncycastle.util.encoders.Base64;
import org.jpos.ee.User;


/**
 * Card generated by hbm2java
 */
public class Key  implements java.io.Serializable {


     private long id;
     private Userdata userdata;
     private JenisKey jenis_key;
     private String key_id;
     private String user_id;
     private String key;
     private Date waktu_buat;
     private Date exp_time;
     private StatusKey status;
     private User user;
     private String key64;
     private String keyHTML;
     private String keyArmor;
     
     
     
     

    public User getUser() {
		return user;
	}



	public void setUser(User user) {
		this.user = user;
	}



	public String getKeyArmor() {
		return keyArmor;
	}

    

	public void setKeyArmor(String keyArmor) {
		this.keyArmor = keyArmor;
	}



	public Key() {
    }



	public long getId() {
		return id;
	}



	public void setId(long id) {
		this.id = id;
	}

    



	public void setUserdata(Userdata user) {
		this.userdata = user;
	}



	public JenisKey getJenis_key() {
		return jenis_key;
	}



	public void setJenis_key(JenisKey jenis_key) {
		this.jenis_key = jenis_key;
	}



	public String getKey_id() {
		return key_id;
	}



	public void setKey_id(String key_id) {
		this.key_id = key_id;
	}



	public String getUser_id() {
		return user_id;
	}



	public void setUser_id(String user_id) {
		this.user_id = user_id;
	}



	public String getKey() {
		return key;
	}



	public String getKeyHTML() {
		return keyHTML;
	}



	public void setKeyHTML(String keyHTML) {
		this.keyHTML = keyHTML;
	}



	public void setKey(String key) {
		this.key = key;
	}



	public Date getWaktu_buat() {
		return waktu_buat;
	}



	public void setWaktu_buat(Date waktu_buat) {
		this.waktu_buat = waktu_buat;
	}



	public StatusKey getStatus() {
		return status;
	}



	public void setStatus(StatusKey status) {
		this.status = status;
	}



	public String getKey64() {
		return key64;
	}



	public void setKey64(String key64) {
		this.key64 = key64;
	}



	public Date getExp_time() {
		return exp_time;
	}



	public void setExp_time(Date exp_time) {
		this.exp_time = exp_time;
	}
    


}


