package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.HashSet;
import java.util.Set;

/**
 * Merchant generated by hbm2java
 */
public class Merchant  implements java.io.Serializable {


     private Long id;
     private String mid;
     private String name;
     private String address;
     private Bank bank;
     private Store store;
     private Partner partner;
     private Set terminal = new HashSet(0);
     private BigDecimal saldo;
     private String username;
     private String pwd;
     private BigDecimal saldoStr;
     private boolean deleted;
     private String ymid;

 	public String getSaldoStr() {
 		DecimalFormat myFormatter = new DecimalFormat("###,###.##");
 		return myFormatter.format(saldo.longValue());
 	}
 	
 	public String getSaldoResp() {
 		DecimalFormat myFormatter = new DecimalFormat("###,###");
 		return myFormatter.format(saldo.longValue()).replace(',', '.');
 	}

 	public Merchant(String mid, String name, Bank bank, Store store, Set terminal) {
        this.mid = mid;
        this.name = name;
        this.bank = bank;
        this.store = store;
        this.terminal = terminal;
        
 	}
    
    public Merchant() {
    	deleted=false;
    }

    
    public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	public void setSaldoStr(BigDecimal saldoStr) {
		this.saldoStr = saldoStr;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public BigDecimal getSaldo() {
		return saldo;
	}

	public void setSaldo(BigDecimal saldo) {
		this.saldo = saldo;

	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

    public Long getId() {
        return this.id;
    }
    
 	public void setId(Long id) {
        this.id = id;
    }
    public String getMid() {
        return this.mid;
    }
    
    public void setMid(String mid) {
        this.mid = mid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }
    public Set getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Set terminal) {
        this.terminal = terminal;
    }

	public Partner getPartner() {
		return partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getYmid() {
		return ymid;
	}

	public void setYmid(String ymid) {
		this.ymid = ymid;
	}
	
}


