package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA



/**
 * Terminal generated by hbm2java
 */
public class NominalAmount  implements java.io.Serializable {


     private Long id;
     private int denom;
     private boolean exist;
     
        public NominalAmount() {
        	exist=false;
        	// TODO Auto-generated constructor stub
		}
     
        
		public boolean isExist() {
			return exist;
		}


		public void setExist(boolean exist) {
			this.exist = exist;
		}


		public Long getId() {
			return id;
		}
		public void setId(Long id) {
			this.id = id;
		}
		public int getDenom() {
			return denom;
		}
		public void setDenom(int denom) {
			this.denom = denom;
		}
     
     
    
    
}


