package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */

public class Nontaglis extends Transaction implements java.io.Serializable {


     private String pln_ref;
     private String switch_ref;
     private String subs_id;
     private String reg_num;
     private String reg_trans;
     private String trans_code;
     private BigDecimal trans_total;
     private BigDecimal pln_bill;
     private BigDecimal admin_charge;
     private String minor_total;
     private String minor_pln;
     private String minor_admin;
     private String minor_amount;
     
    public Nontaglis() {
    }
    
    public Nontaglis(Transaction t){
    	super(t);    	
    }
    

	public Nontaglis(
			String pln_ref, String switch_ref, String subs_id, String reg_num,
			String reg_trans, String trans_code, BigDecimal trans_total,
			BigDecimal pln_bill, BigDecimal admin_charge, String minor_total,
			String minor_pln, String minor_admin, String minor_amount) {
		super();
		this.pln_ref = pln_ref;
		this.switch_ref = switch_ref;
		this.subs_id = subs_id;
		this.reg_num = reg_num;
		this.reg_trans = reg_trans;
		this.trans_code = trans_code;
		this.trans_total = trans_total;
		this.pln_bill = pln_bill;
		this.admin_charge = admin_charge;
		this.minor_total = minor_total;
		this.minor_pln = minor_pln;
		this.minor_admin = minor_admin;
		this.minor_amount = minor_amount;
	}
	




	

	public String getPln_ref() {
		return pln_ref;
	}

	public void setPln_ref(String pln_ref) {
		this.pln_ref = pln_ref;
	}

	public String getSwitch_ref() {
		return switch_ref;
	}

	public void setSwitch_ref(String switch_ref) {
		this.switch_ref = switch_ref;
	}

	public String getSubs_id() {
		return subs_id;
	}

	public void setSubs_id(String subs_id) {
		this.subs_id = subs_id;
	}

	public String getReg_num() {
		return reg_num;
	}

	public void setReg_num(String reg_num) {
		this.reg_num = reg_num;
	}

	public String getReg_trans() {
		return reg_trans;
	}

	public void setReg_trans(String reg_trans) {
		this.reg_trans = reg_trans;
	}

	public String getTrans_code() {
		return trans_code;
	}

	public void setTrans_code(String trans_code) {
		this.trans_code = trans_code;
	}

	public BigDecimal getTrans_total() {
		return trans_total;
	}

	public void setTrans_total(BigDecimal trans_total) {
		this.trans_total = trans_total;
	}

	public BigDecimal getPln_bill() {
		return pln_bill;
	}

	public void setPln_bill(BigDecimal pln_bill) {
		this.pln_bill = pln_bill;
	}

	public BigDecimal getAdmin_charge() {
		return admin_charge;
	}

	public void setAdmin_charge(BigDecimal admin_charge) {
		this.admin_charge = admin_charge;
	}

	public String getMinor_total() {
		return minor_total;
	}

	public void setMinor_total(String minor_total) {
		this.minor_total = minor_total;
	}

	public String getMinor_pln() {
		return minor_pln;
	}

	public void setMinor_pln(String minor_pln) {
		this.minor_pln = minor_pln;
	}

	public String getMinor_admin() {
		return minor_admin;
	}

	public void setMinor_admin(String minor_admin) {
		this.minor_admin = minor_admin;
	}

	public String getMinor_amount() {
		return minor_amount;
	}

	public void setMinor_amount(String minor_amount) {
		this.minor_amount = minor_amount;
	}

    

}


