package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.sql.Blob;
import java.util.Date;

import org.jpos.ee.User;

/**
 * Transaction generated by hbm2java
 */
public class Payment implements java.io.Serializable{

     private Long id;
     private String photo;
     private String product_code;
     private Long	amount;
     private Long	amount_original;
     private String name_source;
     private String bank_from;
     private String bank_to;
     private Date date_request;
     private Date date_confirmation;
     private Date date_update;
     private int status;
     private int jml_ttd;
     private String id_customer;
     private User eeuser;
     private String invoice;
     
     
     public Payment() {
     
     }

    
	public Long getAmount_original() {
		return amount_original;
	}


	public void setAmount_original(Long amount_original) {
		this.amount_original = amount_original;
	}


	public int getJml_ttd() {
		return jml_ttd;
	}


	public void setJml_ttd(int jml_ttd) {
		this.jml_ttd = jml_ttd;
	}


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public String getPhoto() {
		return photo;
	}


	public void setPhoto(String photo) {
		this.photo = photo;
	}


	public String getProduct_code() {
		return product_code;
	}


	public void setProduct_code(String product_code) {
		this.product_code = product_code;
	}


	public Long getAmount() {
		return amount;
	}


	public void setAmount(Long amount) {
		this.amount = amount;
	}


	public String getName_source() {
		return name_source;
	}


	public void setName_source(String name_source) {
		this.name_source = name_source;
	}



	public String getBank_from() {
		return bank_from;
	}


	public void setBank_from(String bank_from) {
		this.bank_from = bank_from;
	}


	public String getBank_to() {
		return bank_to;
	}


	public void setBank_to(String bank_to) {
		this.bank_to = bank_to;
	}


	public Date getDate_request() {
		return date_request;
	}


	public void setDate_request(Date date_request) {
		this.date_request = date_request;
	}


	public Date getDate_confirmation() {
		return date_confirmation;
	}


	public void setDate_confirmation(Date date_confirmation) {
		this.date_confirmation = date_confirmation;
	}


	public Date getDate_update() {
		return date_update;
	}


	public void setDate_update(Date date_update) {
		this.date_update = date_update;
	}


	public int getStatus() {
		return status;
	}

	public String getStatusString() {
		if(status==2) {
			return "Verifikasi Konfirmasi";
					
		}
		if(status==3) {
			return "Selesai";
					
		}
		if(status==4) {
			return "Konfirmasi Gagal";
					
		}
		
		return "Menunggu Pembayaran";
	}


	public void setStatus(int status) {
		this.status = status;
	}


	public String getId_customer() {
		return id_customer;
	}


	public void setId_customer(String id_customer) {
		this.id_customer = id_customer;
	}


	public User getEeuser() {
		return eeuser;
	}


	public void setEeuser(User eeuser) {
		this.eeuser = eeuser;
	}


	public String getInvoice() {
		return invoice;
	}


	public void setInvoice(String invoice) {
		this.invoice = invoice;
	}
}