package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */

public class PostpaidVO extends TransactionVO implements java.io.Serializable {

     private String switch_ref;
     private String subs_id;
     private String bill_period;
     private String minor_amount,type;
     private String electric_bill, bill_amount,incentive, ppn, penalty_fee, admin_charge;
     
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getSwitch_ref() {
		return switch_ref;
	}
	public void setSwitch_ref(String switch_ref) {
		this.switch_ref = switch_ref;
	}
	public String getSubs_id() {
		return subs_id;
	}
	public void setSubs_id(String subs_id) {
		this.subs_id = subs_id;
	}
	public String getBill_period() {
		return bill_period;
	}
	public void setBill_period(String bill_period) {
		this.bill_period = bill_period;
	}
	public String getMinor_amount() {
		return minor_amount;
	}
	public void setMinor_amount(String minor_amount) {
		this.minor_amount = minor_amount;
	}
	public String getElectric_bill() {
		return electric_bill;
	}
	public void setElectric_bill(String electric_bill) {
		this.electric_bill = electric_bill;
	}
	public String getBill_amount() {
		return bill_amount;
	}
	public void setBill_amount(String bill_amount) {
		this.bill_amount = bill_amount;
	}
	public String getIncentive() {
		return incentive;
	}
	public void setIncentive(String incentive) {
		this.incentive = incentive;
	}
	public String getPpn() {
		return ppn;
	}
	public void setPpn(String ppn) {
		this.ppn = ppn;
	}
	public String getPenalty_fee() {
		return penalty_fee;
	}
	public void setPenalty_fee(String penalty_fee) {
		this.penalty_fee = penalty_fee;
	}
	public String getAdmin_charge() {
		return admin_charge;
	}
	public void setAdmin_charge(String admin_charge) {
		this.admin_charge = admin_charge;
	}
	


}


