package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */

public class Postpaid extends Transaction implements java.io.Serializable {

     private String switch_ref;
     private String subs_id;
     private String bill_period;
     private String bill_pay;
     private Long electric_bill;
     private Long bill_amount;
     private Long incentive;
     private Long ppn;
     private Long penalty_fee;
     private Long admin_charge;
     
    public Postpaid() {
    }

    public Postpaid(Transaction tr) {
    	super(tr);
    }
    public Postpaid(Postpaid p) {
    	this.switch_ref = p.getSwitch_ref();
		this.subs_id = p.getSubs_id();
		this.bill_period = p.getBill_period();
		this.bill_pay = p.getBill_pay();
		this.electric_bill = p.getElectric_bill();
		this.bill_amount = p.getBill_amount();
		this.incentive = p.getIncentive();
		this.ppn = p.getPpn();
		this.penalty_fee = p.getPenalty_fee();
		this.admin_charge = p.getAdmin_charge();
    }


	public Postpaid(BigDecimal amount, Long saldo, String cardno, Date approvaltime,
			String approvalcode, String source, String transactiontype,
			String type, Integer tracenumber, boolean onus, Batch batch,
			Bank bank, Feature product, Cassa cassa, 
			String switch_ref, String subs_id, String bill_period,
			String bill_pay, Long electric_bill, Long bill_amount,
			Long incentive, Long ppn, Long penalty_fee, Long admin_charge) {
		super();
		this.switch_ref = switch_ref;
		this.subs_id = subs_id;
		this.bill_period = bill_period;
		this.bill_pay = bill_pay;
		this.electric_bill = electric_bill;
		this.bill_amount = bill_amount;
		this.incentive = incentive;
		this.ppn = ppn;
		this.penalty_fee = penalty_fee;
		this.admin_charge = admin_charge;
	}



    
	public String getSwitch_ref() {
		return switch_ref;
	}

	public void setSwitch_ref(String switch_ref) {
		this.switch_ref = switch_ref;
	}

	public String getSubs_id() {
		return subs_id;
	}

	public void setSubs_id(String subs_id) {
		this.subs_id = subs_id;
	}

	public String getBill_period() {
		return bill_period;
	}

	public void setBill_period(String bill_period) {
		this.bill_period = bill_period;
	}

	public String getBill_pay() {
		return bill_pay;
	}

	public void setBill_pay(String bill_pay) {
		this.bill_pay = bill_pay;
	}

	public Long getElectric_bill() {
		return electric_bill;
	}

	public void setElectric_bill(Long electric_bill) {
		this.electric_bill = electric_bill;
	}

	public Long getBill_amount() {
		return bill_amount;
	}

	public void setBill_amount(Long bill_amount) {
		this.bill_amount = bill_amount;
	}

	public Long getIncentive() {
		return incentive;
	}

	public void setIncentive(Long incentive) {
		this.incentive = incentive;
	}

	public Long getPpn() {
		return ppn;
	}

	public void setPpn(Long ppn) {
		this.ppn = ppn;
	}

	public Long getPenalty_fee() {
		return penalty_fee;
	}

	public void setPenalty_fee(Long penalty_fee) {
		this.penalty_fee = penalty_fee;
	}

	public Long getAdmin_charge() {
		return admin_charge;
	}

	public void setAdmin_charge(Long admin_charge) {
		this.admin_charge = admin_charge;
	}

    
    
    


}


