package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class PrepaidVO extends TransactionVO implements java.io.Serializable {

     private String pln_ref;
     private String switch_ref;
     private String no_meter;
     private String admin_charge;
     private String materai;
     private String ppn;
     private String ppj;
     private String angsuran;
     private String power_purchase;
     private String power_kwh;
     private String token;
     private String subs_id;
     
     

    public String getSubs_id() {
		return subs_id;
	}

	public void setSubs_id(String subs_id) {
		this.subs_id = subs_id;
	}

	public PrepaidVO() {
    }

	public String getPln_ref() {
		return pln_ref;
	}

	public void setPln_ref(String pln_ref) {
		this.pln_ref = pln_ref;
	}

	public String getSwitch_ref() {
		return switch_ref;
	}

	public void setSwitch_ref(String switch_ref) {
		this.switch_ref = switch_ref;
	}

	public String getNo_meter() {
		return no_meter;
	}

	public void setNo_meter(String no_meter) {
		this.no_meter = no_meter;
	}

	public String getAdmin_charge() {
		return admin_charge;
	}

	public void setAdmin_charge(String admin_charge) {
		this.admin_charge = admin_charge;
	}

	public String getMaterai() {
		return materai;
	}

	public void setMaterai(String materai) {
		this.materai = materai;
	}

	public String getPpn() {
		return ppn;
	}

	public void setPpn(String ppn) {
		this.ppn = ppn;
	}

	public String getPpj() {
		return ppj;
	}

	public void setPpj(String ppj) {
		this.ppj = ppj;
	}

	public String getAngsuran() {
		return angsuran;
	}

	public void setAngsuran(String angsuran) {
		this.angsuran = angsuran;
	}

	public String getPower_purchase() {
		return power_purchase;
	}

	public void setPower_purchase(String power_purchase) {
		this.power_purchase = power_purchase;
	}

	public String getPower_kwh() {
		return power_kwh;
	}

	public void setPower_kwh(String power_kwh) {
		this.power_kwh = power_kwh;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

    

    


}


