package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Prepaid extends Transaction implements java.io.Serializable {

     private String pln_ref;
     private String switch_ref;
     private String no_meter;
     private BigDecimal admin_charge;
     private BigDecimal materai;
     private BigDecimal ppn;
     private BigDecimal ppj;
     private BigDecimal angsuran;
     private BigDecimal power_purchase;
     private BigDecimal power_kwh;
     private String token;
     private String minor_amount;
     private String minor_admin;
     private String minor_materai;
     private String minor_ppn;
     private String minor_ppj;
     private String minor_angsuran;
     private String minor_purchase;
     private String minor_kwh;
     private String subs_id;
     private String name;
     private String segment;
     private int daya;
  




	public Prepaid() {
    }

	public Prepaid(Transaction t) {
		super(t);
    }


	public Prepaid(BigDecimal amount, Long saldo, String cardno, Date approvaltime,
			String approvalcode, String source, String productcode,
			String type, Integer tracenumber, boolean onus, Batch batch,
			Bank bank, Feature product, Cassa cassa, 
			String pln_ref, String switch_ref, String no_meter,
			BigDecimal admin_charge, BigDecimal materai, BigDecimal ppn, BigDecimal ppj, BigDecimal angsuran,
			BigDecimal power_purchase, BigDecimal power_kwh, String token,
			String minor_amount, String minor_admin, String minor_materai,
			String minor_ppn, String minor_ppj, String minor_angsuran,
			String minor_purchase, String minor_kwh, String name, String segment, int daya, Transaction tr) {
		super(tr);
		
		this.pln_ref = pln_ref;
		this.switch_ref = switch_ref;
		this.no_meter = no_meter;
		this.admin_charge = admin_charge;
		this.materai = materai;
		this.ppn = ppn;
		this.ppj = ppj;
		this.angsuran = angsuran;
		this.power_purchase = power_purchase;
		this.power_kwh = power_kwh;
		this.token = token;
		this.minor_amount = minor_amount;
		this.minor_admin = minor_admin;
		this.minor_materai = minor_materai;
		this.minor_ppn = minor_ppn;
		this.minor_ppj = minor_ppj;
		this.minor_angsuran = minor_angsuran;
		this.minor_purchase = minor_purchase;
		this.minor_kwh = minor_kwh;
		this.segment=segment;
		this.daya=daya;
		this.name=name;
	}

	   
    

    public String getSubs_id() {
		return subs_id;
	}
	public void setSubs_id(String subs_id) {
		this.subs_id = subs_id;
	}
	public String getPln_ref() {
		return pln_ref;
	}

	public void setPln_ref(String pln_ref) {
		this.pln_ref = pln_ref;
	}

	public String getSwitch_ref() {
		return switch_ref;
	}

	public void setSwitch_ref(String switch_ref) {
		this.switch_ref = switch_ref;
	}

	public String getNo_meter() {
		return no_meter;
	}

	public void setNo_meter(String no_meter) {
		this.no_meter = no_meter;
	}

	public BigDecimal getAdmin_charge() {
		return admin_charge;
	}

	public void setAdmin_charge(BigDecimal admin_charge) {
		this.admin_charge = admin_charge;
	}

	public BigDecimal getMaterai() {
		return materai;
	}

	public void setMaterai(BigDecimal materai) {
		this.materai = materai;
	}

	public BigDecimal getPpn() {
		return ppn;
	}

	public void setPpn(BigDecimal ppn) {
		this.ppn = ppn;
	}

	public BigDecimal getPpj() {
		return ppj;
	}

	public void setPpj(BigDecimal ppj) {
		this.ppj = ppj;
	}

	public BigDecimal getAngsuran() {
		return angsuran;
	}

	public void setAngsuran(BigDecimal angsuran) {
		this.angsuran = angsuran;
	}

	public BigDecimal getPower_purchase() {
		return power_purchase;
	}

	public void setPower_purchase(BigDecimal power_purchase) {
		this.power_purchase = power_purchase;
	}

	public BigDecimal getPower_kwh() {
		return power_kwh;
	}

	public void setPower_kwh(BigDecimal power_kwh) {
		this.power_kwh = power_kwh;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getMinor_amount() {
		return minor_amount;
	}

	public void setMinor_amount(String minor_amount) {
		this.minor_amount = minor_amount;
	}

	public String getMinor_admin() {
		return minor_admin;
	}

	public void setMinor_admin(String minor_admin) {
		this.minor_admin = minor_admin;
	}

	public String getMinor_materai() {
		return minor_materai;
	}

	public void setMinor_materai(String minor_materai) {
		this.minor_materai = minor_materai;
	}

	public String getMinor_ppn() {
		return minor_ppn;
	}

	public void setMinor_ppn(String minor_ppn) {
		this.minor_ppn = minor_ppn;
	}

	public String getMinor_ppj() {
		return minor_ppj;
	}

	public void setMinor_ppj(String minor_ppj) {
		this.minor_ppj = minor_ppj;
	}

	public String getMinor_angsuran() {
		return minor_angsuran;
	}

	public void setMinor_angsuran(String minor_angsuran) {
		this.minor_angsuran = minor_angsuran;
	}

	public String getMinor_purchase() {
		return minor_purchase;
	}

	public void setMinor_purchase(String minor_purchase) {
		this.minor_purchase = minor_purchase;
	}

	public String getMinor_kwh() {
		return minor_kwh;
	}

	public void setMinor_kwh(String minor_kwh) {
		this.minor_kwh = minor_kwh;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSegment() {
		return segment;
	}

	public void setSegment(String segment) {
		this.segment = segment;
	}

	public int getDaya() {
		return daya;
	}

	public void setDaya(int daya) {
		this.daya = daya;
	}
 
    
    


}


