package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Productbillermerchant {

    private Long id;
    Merchant merchant;
    Productbiller productbiller;
	
    
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Merchant getMerchant() {
		return merchant;
	}
	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}
	public Productbiller getProductbiller() {
		return productbiller;
	}
	public void setProductbiller(Productbiller productbiller) {
		this.productbiller = productbiller;
	}


    
 
    
    


}


