package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class ProductBilling  implements java.io.Serializable {


     private long id;
     private String product_code;
     private String jmlh_ttd;
     private String harga;

    public ProductBilling() {
    }

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getProduct_code() {
		return product_code;
	}

	public void setProduct_code(String product_code) {
		this.product_code = product_code;
	}

	public String getJmlh_ttd() {
		return jmlh_ttd;
	}

	public void setJmlh_ttd(String jmlh_ttd) {
		this.jmlh_ttd = jmlh_ttd;
	}

	public String getHarga() {
		return harga;
	}

	public void setHarga(String harga) {
		this.harga = harga;
	}

    



}


