package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Productbiller {

     private Long id;
     private String name;
     private String productbillercode;
     private Feature feature;
     private int harga;
     private int admin;
     private int mitra;
     private int total;
     private int nominal;
     private boolean exist;
     private String productsuppcode;
     private Supplier supplier;
    
     
     public String getProductsuppcode() {
		return productsuppcode;
	}

	public void setProductsuppcode(String productsuppcode) {
		this.productsuppcode = productsuppcode;
	}

	public Supplier getSupplier() {
		return supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	public Productbiller() {
    	 exist=false;
     }
    
	public boolean isExist() {
		return exist;
	}

	public void setExist(boolean exist) {
		this.exist = exist;
	}

	public int getHarga() {
		return harga;
	}

	public int getNominal() {
		return nominal;
	}

	public void setNominal(int nominal) {
		this.nominal = nominal;
	}

	public void setHarga(int harga) {
		this.harga = harga;
	}

	public int getAdmin() {
		return admin;
	}

	public void setAdmin(int admin) {
		this.admin = admin;
	}

	public int getMitra() {
		return mitra;
	}

	public void setMitra(int mitra) {
		this.mitra = mitra;
	}

	public int getTotal() {
		return total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getProductbillercode() {
		return productbillercode;
	}

	public void setProductbillercode(String productbillercode) {
		this.productbillercode = productbillercode;
	}

	public Feature getFeature() {
		return feature;
	}

	public void setFeature(Feature feature) {
		this.feature = feature;
	}
	
	public BigDecimal setHargaPlusAdmin(BigDecimal harga){
		if(admin>0){
			harga=harga.add(new BigDecimal(admin));
		}
		this.harga=harga.intValue();
		return harga;
		
	}

	public BigDecimal getHoldAmount(){
		return new BigDecimal((nominal*1000)+(2000));
	}
 
    
    


}


