package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class PulsaBAK2 extends Transaction implements java.io.Serializable {

     private String msisdn;
     private String sn;
     private String pc;
     private String kode;
     private String harga;
 
	public PulsaBAK2() {
    }
	
	public PulsaBAK2(Transaction t) {
		super(t);
    }
	public String getKode() {
		return kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	public String getHarga() {
		return harga;
	}

	public void setHarga(String harga) {
		this.harga = harga;
	}

	public String getMsisdn() {
		return msisdn;
	}

	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}

	public String getSn() {
		return sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	public String getPc() {
		return pc;
	}

	public void setPc(String pc) {
		this.pc = pc;
	}

	
	
    
 
    
    


}


