package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA



/**
 * Range generated by hbm2java
 */
public class Range  implements java.io.Serializable {


     private long id;
     private long low;
     private long high;
     private Product product;

    public Range() {
    }

    public Range(long low, long high, Product product) {
       this.low = low;
       this.high = high;
       this.product = product;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getLow() {
        return this.low;
    }
    
    public void setLow(long low) {
        this.low = low;
    }
    public long getHigh() {
        return this.high;
    }
    
    public void setHigh(long high) {
        this.high = high;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


