package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Reconciliation generated by hbm2java
 */
public class Reconciliation  implements java.io.Serializable {


     private Long id;
     private String store;
     private Date dateday;
     private Long card;
     private Long cash;
     private Long total;
     private Float percentcard;
     private Float percentcash;

    public Reconciliation() {
    }

    public Reconciliation(String store, Date dateday, Long card, Long cash, Long total, Float percentcard, Float percentcash) {
       this.store = store;
       this.dateday = dateday;
       this.card = card;
       this.cash = cash;
       this.total = total;
       this.percentcard = percentcard;
       this.percentcash = percentcash;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getStore() {
        return this.store;
    }
    
    public void setStore(String store) {
        this.store = store;
    }
    public Date getDateday() {
        return this.dateday;
    }
    
    public void setDateday(Date dateday) {
        this.dateday = dateday;
    }
    public Long getCard() {
        return this.card;
    }
    
    public void setCard(Long card) {
        this.card = card;
    }
    public Long getCash() {
        return this.cash;
    }
    
    public void setCash(Long cash) {
        this.cash = cash;
    }
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }
    public Float getPercentcard() {
        return this.percentcard;
    }
    
    public void setPercentcard(Float percentcard) {
        this.percentcard = percentcard;
    }
    public Float getPercentcash() {
        return this.percentcash;
    }
    
    public void setPercentcash(Float percentcash) {
        this.percentcash = percentcash;
    }




}


