package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store  implements java.io.Serializable {


     private Long id;
     private String name;
     private String location;
     private Set cassa = new HashSet(0);
     private Set merchant = new HashSet(0);
     private Set floor = new HashSet(0);

    public Store() {
    }

    public Store(String name, String location, Set cassa, Set merchant, Set floor) {
       this.name = name;
       this.location = location;
       this.cassa = cassa;
       this.merchant = merchant;
       this.floor = floor;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Set getCassa() {
        return this.cassa;
    }
    
    public void setCassa(Set cassa) {
        this.cassa = cassa;
    }
    public Set getMerchant() {
        return this.merchant;
    }
    
    public void setMerchant(Set merchant) {
        this.merchant = merchant;
    }
    public Set getFloor() {
        return this.floor;
    }
    
    public void setFloor(Set floor) {
        this.floor = floor;
    }




}


