package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Terminal generated by hbm2java
 */
public class SupplierChn  implements java.io.Serializable {

    private Supplier supplier;
    private Long id;
    private String address;
    private String port;
    private String trxchn;
	public Supplier getSupplier() {
		return supplier;
	}
	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getPort() {
		return port;
	}
	public void setPort(String port) {
		this.port = port;
	}
	public String getTrxchn() {
		return trxchn;
	}
	public void setTrxchn(String trxchn) {
		this.trxchn = trxchn;
	}

}


