package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Terminal generated by hbm2java
 */
public class Supplier  implements java.io.Serializable {


    private Long id;
    private String name;
    private String msisdn;
    private String pin;
    private SupplierChn defsupplierchn;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getMsisdn() {
		return msisdn;
	}
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}
	public String getPin() {
		return pin;
	}
	public void setPin(String pin) {
		this.pin = pin;
	}
	public SupplierChn getDefsupplierchn() {
		return defsupplierchn;
	}
	public void setDefsupplierchn(SupplierChn defsupplierchn) {
		this.defsupplierchn = defsupplierchn;
	}


    
    
    
    
}


