package id.co.keriss.consolidate.ee;
// Generated 25 Sep 10 7:16:33 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class TransactionVO  implements java.io.Serializable {


     private Long id;
     private String amount;
     private String cardno;
     private Date approvaltime;
     private String approvalcode;
     private String source;
     private String transactiontype;
     private String type;
     private Long tracenumber;
     private boolean onus;
     private Batch batch;
     private Bank bank;
     private Feature product;
     private Cassa cassa;
     
    public TransactionVO() {
    }

    public TransactionVO(String amount, String cardno, Date approvaltime, String approvalcode, String source, String transactiontype, String type, Long tracenumber, boolean onus, Batch batch, Bank bank, Feature product, Cassa cassa) {
       this.amount = amount;
       this.cardno = cardno;
       this.approvaltime = approvaltime;
       this.approvalcode = approvalcode;
       this.source = source;
       this.transactiontype = transactiontype;
       this.type = type;
       this.tracenumber = tracenumber;
       this.onus = onus;
       this.batch = batch;
       this.bank = bank;
       this.product = product;
       this.cassa = cassa;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getCardno() {
        return this.cardno;
    }
    
    public void setCardno(String cardno) {
        this.cardno = cardno;
    }
    public Date getApprovaltime() {
        return this.approvaltime;
    }
    
    public void setApprovaltime(Date approvaltime) {
        this.approvaltime = approvaltime;
    }
    public String getApprovalcode() {
        return this.approvalcode;
    }
    
    public void setApprovalcode(String approvalcode) {
        this.approvalcode = approvalcode;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getTransactiontype() {
        return this.transactiontype;
    }
    
    public void setTransactiontype(String transactiontype) {
        this.transactiontype = transactiontype;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Long getTracenumber() {
        return this.tracenumber;
    }
    
    public void setTracenumber(Long tracenumber) {
        this.tracenumber = tracenumber;
    }
    public boolean isOnus() {
        return this.onus;
    }
    
    public void setOnus(boolean onus) {
        this.onus = onus;
    }
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }
    public Feature getProduct() {
        return this.product;
    }
    
    public void setProduct(Feature product) {
        this.product = product;
    }
    public Cassa getCassa() {
        return this.cassa;
    }
    
    public void setCassa(Cassa cassa) {
        this.cassa = cassa;
    }




}


