package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction {


     private Long id;
     private BigDecimal amount;
     private String cardno;
     private Date approvaltime;
     private String approvalcode;
     private String source;
     private String productcode;
     private String type;
     private Long tracenumber;
     private boolean onus;
     private Batch batch;
     private Bank bank;
     private Feature product;
     private Cassa cassa;
     private String mcode;
     private String productname;

     private String reqid;
     private String iqpay;
     private String rc;
     private String sn;
     private String msg;
     private BigDecimal depositamount;
     private BigDecimal merchantamount;
     private int admin;
     private int mitra;
     private String productsuppcode;
     private Supplier supplier;


    public Transaction() {
    }

    public Transaction(Long id, BigDecimal amount, String cardno,
			Date approvaltime, String approvalcode, String source,
			String productcode, String type, Long tracenumber,
			boolean onus, Batch batch, Bank bank, Feature product, Cassa cassa,
			String mcode, String reqid, String iqpay, String rc, String sn,
			String msg,BigDecimal depositamount,BigDecimal merchantamount, String productname, Supplier supplier, String productsuppcode) {
		super();
		this.id = id;
		this.amount = amount;
		this.cardno = cardno;
		this.approvaltime = approvaltime;
		this.approvalcode = approvalcode;
		this.source = source;
		this.productcode = productcode;
		this.type = type;
		this.tracenumber = tracenumber;
		this.onus = onus;
		this.batch = batch;
		this.bank = bank;
		this.product = product;
		this.cassa = cassa;
		this.mcode = mcode;
		this.reqid = reqid;
		this.iqpay = iqpay;
		this.rc = rc;
		this.sn = sn;
		this.msg = msg;
		this.depositamount=depositamount;
		this.merchantamount=merchantamount;
		this.productname=productname;
		this.productsuppcode=productsuppcode;
		this.supplier=supplier;
	}
    
	public Transaction(Transaction tr) {
		setTransaction(tr);
	}
	
	public Transaction getTransaction(){
		return this;
	}
	
	public void setTransaction(Transaction tr) {
		if(tr.getId()!=null)this.id = tr.getId();
		this.amount = tr.getAmount();
		this.cardno = tr.getCardno();
		this.approvaltime = tr.getApprovaltime();
		this.approvalcode = tr.getApprovalcode();
		this.source = tr.getSource();
		this.productcode = tr.getProductcode();
		this.type = tr.getType();
		this.tracenumber = tr.getTracenumber();
		this.onus = tr.isOnus();
		this.batch = tr.getBatch();
		this.bank = tr.getBank();
		this.product = tr.getProduct();
		this.cassa = tr.getCassa();
		this.mcode = tr.getMcode();
		this.reqid = tr.getReqid();
		this.iqpay = tr.getIqpay();
		this.rc = tr.getRc();
		this.sn = tr.getSn();
		this.msg = tr.getMsg();
		this.depositamount=tr.getDepositamount();
		this.merchantamount=tr.getMerchantamount();
		this.productname=tr.getProductname();
		this.supplier=tr.getSupplier();
		this.productsuppcode=tr.getProductsuppcode();
		
	}
	
	public String getProductsuppcode() {
		return productsuppcode;
	}

	public void setProductsuppcode(String productsuppcode) {
		this.productsuppcode = productsuppcode;
	}

	public Supplier getSupplier() {
		return supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	public int getAdmin() {
		return admin;
	}

	public void setAdmin(int admin) {
		this.admin = admin;
	}

	public int getMitra() {
		return mitra;
	}

	public String getProductname() {
		return productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public void setMitra(int mitra) {
		this.mitra = mitra;
	}

	public BigDecimal getMerchantamount() {
		return merchantamount;
	}

	public void setMerchantamount(BigDecimal merchantamount) {
		this.merchantamount = merchantamount;
	}

	public BigDecimal getDepositamount() {
		return depositamount;
	}

	public void setDepositamount(BigDecimal depositamount) {
		this.depositamount = depositamount;
	}

	public Long getTracenumber() {
		return tracenumber;
	}

	public void setTracenumber(Long tracenumber) {
		this.tracenumber = tracenumber;
	}

	public String getReqid() {
		return reqid;
	}

	public void setReqid(String reqid) {
		this.reqid = reqid;
	}

	public String getIqpay() {
		return iqpay;
	}

	public void setIqpay(String iqpay) {
		this.iqpay = iqpay;
	}

	public String getRc() {
		return rc;
	}

	public void setRc(String rc) {
		this.rc = rc;
	}

	public String getSn() {
		return sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	public String getMsg() {
		return msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public String getMcode() {
		return mcode;
	}

	public void setMcode(String mcode) {
		this.mcode = mcode;
	}

	public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getCardno() {
        return this.cardno;
    }
    
    public void setCardno(String cardno) {
        this.cardno = cardno;
    }
    public Date getApprovaltime() {
        return this.approvaltime;
    }
    
    public void setApprovaltime(Date approvaltime) {
        this.approvaltime = approvaltime;
    }
    public String getApprovalcode() {
        return this.approvalcode;
    }
    
    public void setApprovalcode(String approvalcode) {
        this.approvalcode = approvalcode;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public String getProductcode() {
		return productcode;
	}

	public void setProductcode(String productcode) {
		this.productcode = productcode;
	}

	public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    public boolean isOnus() {
        return this.onus;
    }
    
    public void setOnus(boolean onus) {
        this.onus = onus;
    }
    public Batch getBatch() {
        return this.batch;
    }
    
    public void setBatch(Batch batch) {
        this.batch = batch;
    }
    public Bank getBank() {
        return this.bank;
    }
    
    public void setBank(Bank bank) {
        this.bank = bank;
    }
    public Feature getProduct() {
        return this.product;
    }
    
    public void setProduct(Feature product) {
        this.product = product;
    }
    public Cassa getCassa() {
        return this.cassa;
    }
    
    public void setCassa(Cassa cassa) {
        this.cassa = cassa;
    }




}


