package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

import com.sun.org.apache.xerces.internal.util.Status;

/**
 * Transaction generated by hbm2java
 */
public class TrxDs {

     private Long id;
     private String message;
     private char type;
     private Date msg_time;
     private Userdata msg_to;
     private Userdata msg_from;
     private StatusKey status;
    
     public TrxDs() {
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public char getType() {
		return type;
	}

	public void setType(char type) {
		this.type = type;
	}

	public Date getMsg_time() {
		return msg_time;
	}

	public void setMsg_time(Date msg_time) {
		this.msg_time = msg_time;
	}

	public Userdata getMsg_to() {
		return msg_to;
	}

	public void setMsg_to(Userdata msg_to) {
		this.msg_to = msg_to;
	}

	public Userdata getMsg_from() {
		return msg_from;
	}

	public void setMsg_from(Userdata msg_from) {
		this.msg_from = msg_from;
	}

	public StatusKey getStatus() {
		return status;
	}

	public void setStatus(StatusKey status) {
		this.status = status;
	}

}


