package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class VerificationTransaction implements java.io.Serializable  {
	 
	 private Long id;
	 private Mitra mitra;
	 private Date msg_time;
     private String nik;
     private boolean result;
     private boolean sendToFaceCheck;
     private boolean sendToDataCheck;
     private String timestampFace;
     private String	timestampData;
     private String msgResp;
     private String msgReq;
     private Long invoice;
     
     
     public VerificationTransaction() {
    	 result=false;
    	 sendToDataCheck=false;
    	 sendToFaceCheck=false;
    	 
    }

	public String getMsgReq() {
		return msgReq;
	}

	public void setMsgReq(String msgReq) {
		this.msgReq = msgReq;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getMsg_time() {
		return msg_time;
	}

	public void setMsg_time(Date msg_time) {
		this.msg_time = msg_time;
	}

	public Mitra getMitra() {
		return mitra;
	}

	public void setMitra(Mitra mitra) {
		this.mitra = mitra;
	}

	public String getNik() {
		return nik;
	}

	public void setNik(String nik) {
		this.nik = nik;
	}

	public boolean isResult() {
		return result;
	}

	public void setResult(boolean result) {
		this.result = result;
	}



	public boolean isSendToFaceCheck() {
		return sendToFaceCheck;
	}

	public void setSendToFaceCheck(boolean sendToFaceCheck) {
		this.sendToFaceCheck = sendToFaceCheck;
	}

	public boolean isSendToDataCheck() {
		return sendToDataCheck;
	}

	public void setSendToDataCheck(boolean sendToDataCheck) {
		this.sendToDataCheck = sendToDataCheck;
	}

	public String getTimestampFace() {
		return timestampFace;
	}

	public void setTimestampFace(String timestampFace) {
		this.timestampFace = timestampFace;
	}

	public String getTimestampData() {
		return timestampData;
	}

	public void setTimestampData(String timestampData) {
		this.timestampData = timestampData;
	}

	public String getMsgResp() {
		return msgResp;
	}

	public void setMsgResp(String msgResp) {
		this.msgResp = msgResp;
	}

	public Long getInvoice() {
		return invoice;
	}

	public void setInvoice(Long invoice) {
		this.invoice = invoice;
	}

	

}


