package id.co.keriss.consolidate.ee;
// Generated 30 Nov 11 0:33:41 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Terminal generated by hbm2java
 */
public class Wl_Villages  implements java.io.Serializable {

    private String id;
    private String district_id;
    private String name;
    private String kodepos;

    public Wl_Villages(){
    	
    }
    
    public Wl_Villages(String id,String district_id, String name,String kodepos) {
       this.id = id;
       this.district_id = district_id;
       this.name = name;
       this.kodepos = kodepos;
    }

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDistrict_id() {
		return district_id;
	}

	public void setDistrict_id(String district_id) {
		this.district_id = district_id;
	}

	public String getKodepos() {
		return kodepos;
	}

	public void setKodepos(String kodepos) {
		this.kodepos = kodepos;
	}

	
		
}


